sudo: required
services:
  - docker

before_install:
  - docker build -t olegdimitrov1/react-test -f ./client/Dockerfile.dev ./client/


script:
  - docker run olegdimitrov1/react-test npm test -- --coverage

after_success:
  - docker build -t olegdimitrov1/multi-client ./client
  - docker build -t olegdimitrov1/multi-nginx ./nginx
  - docker build -t olegdimitrov1/multi-server ./server
  - docker build -t olegdimitrov1/multi-worker ./worker

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push olegdimitrov1/multi-client
  - docker push olegdimitrov1/multi-nginx
  - docker push olegdimitrov1/multi-server
  - docker push olegdimitrov1/multi-worker

